### ISSUE TITLE
unable to switch modes, service is not running in openrc

### ISSUE THREAD

**Issue by qundus** [Askannz/optimus-manager#514]
**Describe the bug**
when i try to issue command `optimus-manager --switch nvidia|hybri|integrated` i get the following message:
```terminal
The optimus-manager service is not running. Please enable and start it as described at Artix Linux Wiki, and reboot
```
i'm using `lightdm` display manager with `openrc` init system and i've  installd and activated optimus manager init scripts for both lightdm and optimus-manager services, also, i've tried adding adding  the services to all run-levels of openrc with no use, please help with this.

**System info**
```yaml
OS: Artix Linux x86_64
Host: Dell G15 5515 1.4.0
Kernel: 5.19.6-artix1-1
Uptime: 20 mins
Packages: 1219 (pacman)
Shell: bash 5.1.16
Resolution: 1920x1080, 1920x1080
DE: Cinnamon 5.4.12
WM: Mutter
WM Theme: Adwaita
Theme: Adwaita-dark [GTK2/3]
Icons: Apricity Icons [GTK2/3]
Terminal: alacritty
Terminal Font: Menlo
CPU: AMD Ryzen 5 5600H with Radeon Graphics (12) @ 3.300GHz
GPU: AMD ATI 05:00.0 Cezanne
GPU: NVIDIA GeForce RTX 3050 Mobile
Memory: 2000MiB / 7291MiB

DM: lightdm 1.32.0
Model: Dell G15 Ryzen Edition
OM: optimus-manager-git
```

i haven't modified `/etc/optimus-manager/optimus-manager.conf`
**Logs**
```log
Optimus Manager (Client) version 1.4

Current GPU mode : hybrid
GPU mode requested for next login : no change
GPU at startup : hybrid
Temporary config path: no
```

**Reproduction**
just install the `optimus-manager-git` package and try to switch between modes, if it works for you please share your system info.
